version: "3"

services:
  baguette:
    build: .
    container_name: bot
    restart: always
    ports:
      - ${DEBUG_PORT}:5678
    depends_on:
      - mongo
    volumes:
      - .:/usr/baguette

  mongo:
    image: mongo:7.0.9
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./var/mongo/data:/data/db
      - ./var/mongo/mongod.conf:/etc/mongo/mongod.conf:ro
    command: --config /etc/mongo/mongod.conf

  duckling:
    image: rasa/duckling
    container_name: duckling
    restart: always
    ports:
      - ${DUCKLING_PORT}:8000
