version: "3"

services:
  baguette:
    build: .
    container_name: bot
    restart: always
    ports:
      # debug adapter
      - 5678:5678
    depends_on:
      - mongo
    volumes:
      - .:/usr/baguette

  mongo:
    image: mongo:7.0.9
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - ./var/mongo_data:/data/db

  duckling:
    image: rasa/duckling
    container_name: duckling
    restart: always
    ports:
      - 8000:8000
